/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppThirdPartyRouteImport } from './routes/app.third-party'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQuotationsRouteImport } from './routes/app.quotations'
import { Route as AppPurchasesRouteImport } from './routes/app.purchases'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPrintRouteImport } from './routes/app.print'
import { Route as AppPriceListsRouteImport } from './routes/app.price-lists'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppLookupRouteImport } from './routes/app.lookup'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppGuideRouteImport } from './routes/app.guide'
import { Route as AppGstRouteImport } from './routes/app.gst'
import { Route as AppFixedAssetsRouteImport } from './routes/app.fixed-assets'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppDeliveriesRouteImport } from './routes/app.deliveries'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppBuyersRouteImport } from './routes/app.buyers'
import { Route as AppBillsRouteImport } from './routes/app.bills'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppPrintQuoteIdRouteImport } from './routes/app.print.quote.$id'
import { Route as AppPrintInvoiceIdRouteImport } from './routes/app.print.invoice.$id'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThirdPartyRoute = AppThirdPartyRouteImport.update({
  id: '/app/third-party',
  path: '/app/third-party',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/app/suppliers',
  path: '/app/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/app/stock',
  path: '/app/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/app/sales',
  path: '/app/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/app/quotations',
  path: '/app/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/app/purchases',
  path: '/app/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/app/products',
  path: '/app/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPrintRoute = AppPrintRouteImport.update({
  id: '/app/print',
  path: '/app/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPriceListsRoute = AppPriceListsRouteImport.update({
  id: '/app/price-lists',
  path: '/app/price-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/app/payments',
  path: '/app/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLookupRoute = AppLookupRouteImport.update({
  id: '/app/lookup',
  path: '/app/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/app/ledger',
  path: '/app/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/app/guide',
  path: '/app/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGstRoute = AppGstRouteImport.update({
  id: '/app/gst',
  path: '/app/gst',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFixedAssetsRoute = AppFixedAssetsRouteImport.update({
  id: '/app/fixed-assets',
  path: '/app/fixed-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/app/expenses',
  path: '/app/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeliveriesRoute = AppDeliveriesRouteImport.update({
  id: '/app/deliveries',
  path: '/app/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/app/contacts',
  path: '/app/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBuyersRoute = AppBuyersRouteImport.update({
  id: '/app/buyers',
  path: '/app/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/app/bills',
  path: '/app/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/app/audit',
  path: '/app/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/app/analytics',
  path: '/app/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPrintQuoteIdRoute = AppPrintQuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => AppPrintRoute,
} as any)
const AppPrintInvoiceIdRoute = AppPrintInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => AppPrintRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bills': typeof AppBillsRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/deliveries': typeof AppDeliveriesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/fixed-assets': typeof AppFixedAssetsRoute
  '/app/gst': typeof AppGstRoute
  '/app/guide': typeof AppGuideRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/price-lists': typeof AppPriceListsRoute
  '/app/print': typeof AppPrintRouteWithChildren
  '/app/products': typeof AppProductsRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stock': typeof AppStockRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/third-party': typeof AppThirdPartyRoute
  '/app/': typeof AppIndexRoute
  '/app/print/invoice/$id': typeof AppPrintInvoiceIdRoute
  '/app/print/quote/$id': typeof AppPrintQuoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bills': typeof AppBillsRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/deliveries': typeof AppDeliveriesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/fixed-assets': typeof AppFixedAssetsRoute
  '/app/gst': typeof AppGstRoute
  '/app/guide': typeof AppGuideRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/price-lists': typeof AppPriceListsRoute
  '/app/print': typeof AppPrintRouteWithChildren
  '/app/products': typeof AppProductsRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stock': typeof AppStockRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/third-party': typeof AppThirdPartyRoute
  '/app': typeof AppIndexRoute
  '/app/print/invoice/$id': typeof AppPrintInvoiceIdRoute
  '/app/print/quote/$id': typeof AppPrintQuoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bills': typeof AppBillsRoute
  '/app/buyers': typeof AppBuyersRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/deliveries': typeof AppDeliveriesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/fixed-assets': typeof AppFixedAssetsRoute
  '/app/gst': typeof AppGstRoute
  '/app/guide': typeof AppGuideRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/price-lists': typeof AppPriceListsRoute
  '/app/print': typeof AppPrintRouteWithChildren
  '/app/products': typeof AppProductsRoute
  '/app/purchases': typeof AppPurchasesRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stock': typeof AppStockRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/third-party': typeof AppThirdPartyRoute
  '/app/': typeof AppIndexRoute
  '/app/print/invoice/$id': typeof AppPrintInvoiceIdRoute
  '/app/print/quote/$id': typeof AppPrintQuoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/index'
    | '/login'
    | '/app/analytics'
    | '/app/audit'
    | '/app/bills'
    | '/app/buyers'
    | '/app/contacts'
    | '/app/deliveries'
    | '/app/expenses'
    | '/app/fixed-assets'
    | '/app/gst'
    | '/app/guide'
    | '/app/ledger'
    | '/app/lookup'
    | '/app/payments'
    | '/app/price-lists'
    | '/app/print'
    | '/app/products'
    | '/app/purchases'
    | '/app/quotations'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/stock'
    | '/app/suppliers'
    | '/app/third-party'
    | '/app/'
    | '/app/print/invoice/$id'
    | '/app/print/quote/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/index'
    | '/login'
    | '/app/analytics'
    | '/app/audit'
    | '/app/bills'
    | '/app/buyers'
    | '/app/contacts'
    | '/app/deliveries'
    | '/app/expenses'
    | '/app/fixed-assets'
    | '/app/gst'
    | '/app/guide'
    | '/app/ledger'
    | '/app/lookup'
    | '/app/payments'
    | '/app/price-lists'
    | '/app/print'
    | '/app/products'
    | '/app/purchases'
    | '/app/quotations'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/stock'
    | '/app/suppliers'
    | '/app/third-party'
    | '/app'
    | '/app/print/invoice/$id'
    | '/app/print/quote/$id'
  id:
    | '__root__'
    | '/'
    | '/index'
    | '/login'
    | '/app/analytics'
    | '/app/audit'
    | '/app/bills'
    | '/app/buyers'
    | '/app/contacts'
    | '/app/deliveries'
    | '/app/expenses'
    | '/app/fixed-assets'
    | '/app/gst'
    | '/app/guide'
    | '/app/ledger'
    | '/app/lookup'
    | '/app/payments'
    | '/app/price-lists'
    | '/app/print'
    | '/app/products'
    | '/app/purchases'
    | '/app/quotations'
    | '/app/reports'
    | '/app/sales'
    | '/app/settings'
    | '/app/stock'
    | '/app/suppliers'
    | '/app/third-party'
    | '/app/'
    | '/app/print/invoice/$id'
    | '/app/print/quote/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  LoginRoute: typeof LoginRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillsRoute: typeof AppBillsRoute
  AppBuyersRoute: typeof AppBuyersRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDeliveriesRoute: typeof AppDeliveriesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFixedAssetsRoute: typeof AppFixedAssetsRoute
  AppGstRoute: typeof AppGstRoute
  AppGuideRoute: typeof AppGuideRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppLookupRoute: typeof AppLookupRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppPriceListsRoute: typeof AppPriceListsRoute
  AppPrintRoute: typeof AppPrintRouteWithChildren
  AppProductsRoute: typeof AppProductsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStockRoute: typeof AppStockRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppThirdPartyRoute: typeof AppThirdPartyRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/third-party': {
      id: '/app/third-party'
      path: '/app/third-party'
      fullPath: '/app/third-party'
      preLoaderRoute: typeof AppThirdPartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/app/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/app/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/app/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/app/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/purchases': {
      id: '/app/purchases'
      path: '/app/purchases'
      fullPath: '/app/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/products': {
      id: '/app/products'
      path: '/app/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/print': {
      id: '/app/print'
      path: '/app/print'
      fullPath: '/app/print'
      preLoaderRoute: typeof AppPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/price-lists': {
      id: '/app/price-lists'
      path: '/app/price-lists'
      fullPath: '/app/price-lists'
      preLoaderRoute: typeof AppPriceListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/app/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lookup': {
      id: '/app/lookup'
      path: '/app/lookup'
      fullPath: '/app/lookup'
      preLoaderRoute: typeof AppLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/app/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/guide': {
      id: '/app/guide'
      path: '/app/guide'
      fullPath: '/app/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/gst': {
      id: '/app/gst'
      path: '/app/gst'
      fullPath: '/app/gst'
      preLoaderRoute: typeof AppGstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/fixed-assets': {
      id: '/app/fixed-assets'
      path: '/app/fixed-assets'
      fullPath: '/app/fixed-assets'
      preLoaderRoute: typeof AppFixedAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/app/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/deliveries': {
      id: '/app/deliveries'
      path: '/app/deliveries'
      fullPath: '/app/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/app/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/buyers': {
      id: '/app/buyers'
      path: '/app/buyers'
      fullPath: '/app/buyers'
      preLoaderRoute: typeof AppBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bills': {
      id: '/app/bills'
      path: '/app/bills'
      fullPath: '/app/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/app/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/print/quote/$id': {
      id: '/app/print/quote/$id'
      path: '/quote/$id'
      fullPath: '/app/print/quote/$id'
      preLoaderRoute: typeof AppPrintQuoteIdRouteImport
      parentRoute: typeof AppPrintRoute
    }
    '/app/print/invoice/$id': {
      id: '/app/print/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/app/print/invoice/$id'
      preLoaderRoute: typeof AppPrintInvoiceIdRouteImport
      parentRoute: typeof AppPrintRoute
    }
  }
}

interface AppPrintRouteChildren {
  AppPrintInvoiceIdRoute: typeof AppPrintInvoiceIdRoute
  AppPrintQuoteIdRoute: typeof AppPrintQuoteIdRoute
}

const AppPrintRouteChildren: AppPrintRouteChildren = {
  AppPrintInvoiceIdRoute: AppPrintInvoiceIdRoute,
  AppPrintQuoteIdRoute: AppPrintQuoteIdRoute,
}

const AppPrintRouteWithChildren = AppPrintRoute._addFileChildren(
  AppPrintRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  LoginRoute: LoginRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillsRoute: AppBillsRoute,
  AppBuyersRoute: AppBuyersRoute,
  AppContactsRoute: AppContactsRoute,
  AppDeliveriesRoute: AppDeliveriesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFixedAssetsRoute: AppFixedAssetsRoute,
  AppGstRoute: AppGstRoute,
  AppGuideRoute: AppGuideRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppLookupRoute: AppLookupRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppPriceListsRoute: AppPriceListsRoute,
  AppPrintRoute: AppPrintRouteWithChildren,
  AppProductsRoute: AppProductsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStockRoute: AppStockRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppThirdPartyRoute: AppThirdPartyRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
