ALTER FUNCTION public.tg_contacts_autocode() SECURITY DEFINER;
ALTER FUNCTION public.tg_products_autocode() SECURITY DEFINER;
ALTER FUNCTION public.tg_sales_autonum() SECURITY DEFINER;
ALTER FUNCTION public.tg_purchases_autonum() SECURITY DEFINER;
ALTER FUNCTION public.tg_tp_autonum() SECURITY DEFINER;
ALTER FUNCTION public.tg_quote_autonum() SECURITY DEFINER;
ALTER FUNCTION public.tg_payments_autonum() SECURITY DEFINER;
ALTER FUNCTION public.tg_deliveries_autonum() SECURITY DEFINER;
ALTER FUNCTION public.tg_sale_post() SECURITY DEFINER;
ALTER FUNCTION public.tg_sale_items_post() SECURITY DEFINER;
ALTER FUNCTION public.tg_purchase_post() SECURITY DEFINER;
ALTER FUNCTION public.tg_purchase_items_post() SECURITY DEFINER;
ALTER FUNCTION public.tg_tp_post() SECURITY DEFINER;
ALTER FUNCTION public.tg_tp_items_post() SECURITY DEFINER;
ALTER FUNCTION public.tg_payment_post() SECURITY DEFINER;
ALTER FUNCTION public.tg_expense_post() SECURITY DEFINER;

REVOKE EXECUTE ON FUNCTION public.tg_contacts_autocode() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_products_autocode() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_sales_autonum() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_purchases_autonum() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_tp_autonum() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_quote_autonum() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_payments_autonum() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_deliveries_autonum() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_sale_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_sale_items_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_purchase_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_purchase_items_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_tp_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_tp_items_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_payment_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tg_expense_post() FROM PUBLIC, anon, authenticated;